modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="custom_turrets"
version="0.1"
displayName="Custom Turrets Mod"
authors="Bio Hazard"
description='''Adds placeable turrets that can shoot and rotate.'''

[[dependencies.custom_turrets]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.custom_turrets]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
